{"content": {"suites": {"0": {"status": {"total_pass": 3, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 6, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_TC_OD001_subscribes_to_scan_topic", "rerun": "0"}, "1": {"status": "FAIL", "message": "   TypeError: can only assign array (not \"list\") to array slice\n", "test_name": "test_TC_OD002_processes_ROI_data", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_TC_OD003_publishes_masked_scan", "rerun": "0"}, "3": {"status": "FAIL", "message": "       IndexError: array index out of range\n", "test_name": "test_TC_OD004_detects_obstacle_in_ROI", "rerun": "0"}, "4": {"status": "FAIL", "message": "       IndexError: array index out of range\n", "test_name": "test_TC_OD005_publishes_obstacle_status_true", "rerun": "0"}, "5": {"status": "FAIL", "message": "       IndexError: array index out of range\n", "test_name": "test_TC_OD006_logs_warning_on_obstacle", "rerun": "0"}, "6": {"status": "FAIL", "message": "   AssertionError: Info log not generated for no obstacles.\n   assert 'No obstacles detected' in ''\n    +  where '' = <_pytest.logging.LogCaptureFixture object at 0xffff63016610>.text\n", "test_name": "test_TC_OD007_logs_info_on_no_obstacles", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_TC_OD008_calculates_dynamic_indices", "rerun": "0"}, "8": {"status": "FAIL", "message": "       AssertionError: The 'ranges' field must be a set or sequence and each value of type 'float'\n", "test_name": "test_TC_OD009_logs_errors_on_invalid_data", "rerun": "0"}}, "suite_name": "test/test_obstacle_detection.py"}}}, "date": "December 17, 2024", "start_time": 1734440479.5441658, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "3", "fail": "6", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "9"}